### ISSUE TITLE
Task List 06/05/2019

### ISSUE THREAD

**Issue by cseale** [cseale/fix-it-in-post.net#15]
-  [ ] Fix model saving to use recommended approach (see synthesis notebook) 
 - [x] Use white noise instead of babble noise
 - [ ] Continue Building Metrics
 - [ ] Train model with full dataset using SageMaker/S3
 - [ ] Refine current architectures using the denoising experiments paper

**Comment by cseale** [comment]
Subtasks for S3 work:
- [ ] Create larger notebook instance
- [ ] Upload subset of training data to s3
- [ ] Update preprocessing script to only process this subset
- [ ] Store processed data on s3
- [ ] Run training against full dataset
- [ ] Fix permissions such that everyone can access and push to s3
